#!/bin/sh

APP=beehive
LIBDIR=$(erl -eval 'io:format("~s~n", [code:lib_dir()])' -s init stop -noshell)
VERSION="0.1"
INSTALLED_DIR=$LIBDIR/$APP-$VERSION
SCRIPT_DIR="$(dirname $0)"

if [ -d $INSTALLED_DIR ]; then
  BEEHIVE_HOME=$INSTALLED_DIR/
else
  BEEHIVE_HOME="$SCRIPT_DIR/../"
fi