#!/bin/sh

APP=beehive
LIBDIR=$(erl -eval 'io:format("~s~n", [code:lib_dir()])' -s init stop -noshell)
VERSION="0.1"
INSTALLED_DIR=$LIBDIR/$APP-$VERSION
SCRIPT_DIR=$(dirname $0)
BEEHIVE_PREFIX=''
if [ -z $BEEHIVE_HOME ]; then
  export BEEHIVE_HOME=$(BEEHIVE_PREFIX)/var/lib/beehive
fi
if [ -z $BEEHIVE_SRC ]; then
  if [ -d $INSTALLED_DIR ]; then
    BEEHIVE_SRC=$INSTALLED_DIR
  else
    BEEHIVE_SRC="$SCRIPT_DIR/.."
  fi
fi