#!/bin/sh

. `dirname $0`/beehive_env

ERL_OPTS="-pa $BEEHIVE_HOME/ebin -pa $BEEHIVE_HOME/include -pz $BEEHIVE_HOME/deps/*/ebin"
HOSTNAME=`hostname -f`
NAME=control@$HOSTNAME

exec erl \
    -pa "${BEEHIVE_HOME}/ebin" \
    -noinput \
    -hidden \
    $ERL_OPTS \
    -name $NAME \
    -s beehive_control \
    -extra "$@"