#!/bin/sh

. `dirname $0`/beehive_env

ERL_OPTS="-pa $BEEHIVE_SRC/ebin -pa $BEEHIVE_SRC/include -pz $BEEHIVE_SRC/deps/*/ebin"
HOSTNAME=`hostname -f`
NAME=control@$HOSTNAME

exec erl \
    -noinput \
    -hidden \
    $ERL_OPTS \
    -name $NAME \
    -s beehive_control \
    -extra "$@"